Dyd.BaseService.TaskManager.Web/Controllers/LogController.cs
using Dyd.BaseService.TaskManager.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XXF.Db;
using Dyd.BaseService.TaskManager.Domain.Model;
using Dyd.BaseService.TaskManager.Domain.Dal;
using Webdiyer.WebControls.Mvc;

namespace Dyd.BaseService.TaskManager.Web.Controllers
{
    [Authorize]
    public class LogController : BaseWebController
    {
        //
        // GET: /Log/
        public ActionResult ErrorLog(string keyword, string CStime, string CEtime, int id = -1, int errortype = -1, int taskid = -1, int nodeid = -1, int pagesize = 10, int pageindex = 1)
        {
            return this.Visit(Core.EnumUserRole.None, () =>
            {
                int count = 0;
                using (DbConn PubConn = DbConfig.CreateConn(Config.TaskConnectString))
                {
                    ViewBag.keyword = keyword; ViewBag.CStime = CStime; ViewBag.CEtime = CEtime; ViewBag.id = id; ViewBag.errortype = errortype; ViewBag.taskid = taskid;
                    ViewBag.nodeid = nodeid; ViewBag.pagesize = pagesize; ViewBag.pageindex = pageindex;
                    PubConn.Open();
                    tb_error_dal dal = new tb_error_dal();
                    List<tb_errorinfo_model> model = dal.GetList(PubConn, keyword, id, CStime, CEtime, errortype, taskid, nodeid, pagesize, pageindex, out count);
                    PagedList<tb_errorinfo_model> pageList = new PagedList<tb_errorinfo_model>(model, pageindex, pagesize, count);
                    List<tb_task_model> Task = new tb_task_dal().GetListAll(PubConn);
                    List<tb_node_model> Node = new tb_node_dal().GetListAll(PubConn);
                    ViewBag.Node = Node;
                    ViewBag.Task = Task;
                    return View(pageList);
                }
            });
        }

        public ActionResult Log(string keyword, string CStime, string CEtime, int id = -1, int logtype = -1, int taskid = -1, int nodeid = -1, int pagesize = 10, int pageindex = 1)
        {
            return this.Visit(Core.EnumUserRole.None, () =>
            {
                ViewBag.keyword = keyword; ViewBag.CStime = CStime; ViewBag.CEtime = CEtime; ViewBag.id = id; ViewBag.logtype = logtype; ViewBag.taskid = taskid;
                ViewBag.nodeid = nodeid; ViewBag.pagesize = pagesize; ViewBag.pageindex = pageindex;
                int count = 0;
                using (DbConn PubConn = DbConfig.CreateConn(Config.TaskConnectString))
                {
                    PubConn.Open();
                    tb_log_dal dal = new tb_log_dal();
                    List<tb_loginfo_model> model = dal.GetList(PubConn, keyword, id, CStime, CEtime, logtype, taskid, nodeid, pagesize, pageindex, out count);
                    PagedList<tb_loginfo_model> pageList = new PagedList<tb_loginfo_model>(model, pageindex, pagesize, count);
                    List<tb_task_model> Task = new tb_task_dal().GetListAll(PubConn);
                    List<tb_node_model> Node = new tb_node_dal().GetListAll(PubConn);
                    ViewBag.Node = Node;
                    ViewBag.Task = Task;
                    return View(pageList);
                }
            });
        }
    }
}

Dyd.BaseService.TaskManager.Web/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dyd.BaseService.TaskManager.Domain.Model;
using Dyd.BaseService.TaskManager.Domain.Dal;
using XXF.Db;
using Dyd.BaseService.TaskManager.Web.Models;
using Webdiyer.WebControls.Mvc;
using System.Drawing;
using System.IO;
using Dyd.BaseService.TaskManager.Core;
using XXF.Extensions;

namespace Dyd.BaseService.TaskManager.Web.Controllers
{
    [Authorize]
    public class TaskController : BaseWebController
    {
        //
        // GET: /Task/

        public ActionResult Index(string taskid, string keyword, string CStime,string CEtime, int categoryid = -1, int nodeid = -1, int userid = -1, int state = -999, int pagesize = 10, int pageindex = 1)
        {
            return this.Visit(Core.EnumUserRole.None, () =>
            {
                ViewBag.taskid = taskid;
                ViewBag.keyword = keyword;
                ViewBag.CStime = CStime;
                ViewBag.CEtime = CEtime;
                ViewBag.categoryid = categoryid;
                ViewBag.nodeid = nodeid;
                ViewBag.userid = userid;
                ViewBag.state = state;
                ViewBag.pagesize = pagesize;
                ViewBag.pageindex = pageindex;

                tb_task_dal dal = new tb_task_dal();
                PagedList<tb_tasklist_model> pageList = null;
                int count = 0;
                using (DbConn PubConn = DbConfig.CreateConn(Config.TaskConnectString))
                {
                    PubConn.Open();
                    List<tb_tasklist_model> List = dal.GetList(PubConn,taskid, keyword, CStime,CEtime, categoryid, nodeid, userid, state, pagesize, pageindex, out count);
                    pageList = new PagedList<tb_tasklist_model>(List, pageindex, pagesize, count);
                    List<tb_node_model> Node = new tb_node_dal().GetListAll(PubConn);
                    List<tb_category_model> Category = new tb_category_dal().GetList(PubConn, "");
                    List<tb_user_model> User = new tb_user_dal().GetAllUsers(PubConn);
                    ViewBag.Node = Node;
                    ViewBag.Category = Category;
                    ViewBag.User = User;
                }
                return View(pageList);
            });
        }

        public ActionResult Add()
        {
            return this.Visit(Core.EnumUserRole.Admin, () =>
            {
                using (DbConn PubConn = DbConfig.CreateConn(Config.TaskConnectString))
                {
                    PubConn.Open();
                    List<tb_category_model> Category = new tb_category_dal().GetList(PubConn, "");
                    List<tb_node_model> Node = new tb_node_dal().GetListAll(PubConn);
                    List<tb_user_model> User = new tb_user_dal().GetAllUsers(PubConn);
                    ViewBag.Node = Node;
                    ViewBag.Category = Category;
                    ViewBag.User = User;
                    return View();
                }
            });
        }

        
        public JsonResult CalcRunTime(string CronExpression,int count=5)
        {
            Quartz.CronTrigger trigger = new Quartz.CronTrigger();
            trigger.CronExpressionString = CronExpression;
            List<string> list = new List<string>();
            //注意：这里是utc时间
            trigger.StartTimeUtc = DateTime.UtcNow;
            DateTime? now = trigger.StartTimeUtc;
            for (int i = 0; i < count; i++)
            {
                now = trigger.GetFireTimeAfter(now);
                //要转回本地时间
                list.Add(TimeZone.CurrentTimeZone.ToLocalTime(now.Value).ToString("yyyy/M/d HH:mm:ss"));

            }
            return Json(list,JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Add(HttpPostedFileBase TaskDll, tb_task_model model, string tempdatajson)
        {
            return this.Visit(Core.EnumUserRole.Admin, () =>
            {
                string filename = TaskDll.FileName;
                Stream dll = TaskDll.InputStream;
                byte[] dllbyte = new byte[dll.Length];
                dll.Read(dllbyte, 0, Convert.ToInt32(dll.Length));
                tb_task_dal dal = new tb_task_dal();
                tb_version_dal dalversion = new tb_version_dal();
                tb_tempdata_dal tempdatadal = new tb_tempdata_dal();
                //model.taskcreateuserid = Common.GetUserId(this);
                using (DbConn PubConn = DbConfig.CreateConn(Config.TaskConnectString))
                {
                    PubConn.Open();
                    model.taskcreatetime = DateTime.Now;
                    model.taskversion = 1;
                    int taskid = dal.AddTask(PubConn, model);
                    dalversion.Add(PubConn, new tb_version_model()
                    {
                        taskid = taskid,
                        version = 1,
                        versioncreatetime = DateTime.Now,
                        zipfile = dllbyte,
                        zipfilename = System.IO.Path.GetFileName(filename)
                    });
                    tempdatadal.Add(PubConn, new tb_tempdata_model()
                    {
                        taskid = taskid,
                        tempdatajson = tempdatajson,
                        tempdatalastupdatetime = DateTime.Now
                    });
                }
                return RedirectToAction("index");
            });
        }

        public ActionResult Update(int taskid)
        {
            return this.Visit(Core.EnumUserRole.None, () =>
            {
                using (DbConn PubConn = DbConfig.CreateConn(Config.TaskConnectString))
                {
                    PubConn.Open();
                    tb_task_dal dal = new tb_task_dal();
                    tb_task_model model = dal.GetOneTask(PubConn, taskid);
                    tb_tempdata_model tempdatamodel = new tb_tempdata_dal().GetByTaskID(PubConn, taskid);
                    List<tb_version_model> Version = new tb_version_dal().GetTaskVersion(PubConn, taskid);
                    List<tb_category_model> Category = new tb_category_dal().GetList(PubConn, "");
                    List<tb_node_model> Node = new tb_node_dal().GetListAll(PubConn);
                    List<tb_user_model> User = new tb_user_dal().GetAllUsers(PubConn);
                    ViewBag.Node = Node;
                    ViewBag.Category = Category;
                    ViewBag.Version = Version;
                    ViewBag.User = User;
                    ViewBag.TempData = tempdatamodel;
                    return View(model);
                }
            });
        }

        [HttpPost]
        public ActionResult Update(HttpPostedFileBase TaskDll, tb_task_model model, string tempdatajson)
        {
            return this.Visit(Core.EnumUserRole.Admin, () =>
            {
                try
                {
                    tb_task_dal dal = new tb_task_dal();
                    tb_version_dal dalversion = new tb_version_dal();
                    tb_tempdata_dal tempdatadal = new tb_tempdata_dal();
                    byte[] dllbyte = null;
                    string filename = "";
                    int change = model.taskversion;
                    if (change == -1)
                    {
                        if (TaskDll == null)
                        {
                            throw new Exception("没有文件！");
                        }
                        filename = TaskDll.FileName;
                        Stream dll = TaskDll.InputStream;
                        dllbyte = new byte[dll.Length];
                        dll.Read(dllbyte, 0, Convert.ToInt32(dll.Length));
                        //model.taskcreateuserid = Common.GetUserId(this);
                    }
                    using (DbConn PubConn = DbConfig.CreateConn(Config.TaskConnectString))
                    {
                        PubConn.Open();
                        var task = dal.GetOneTask(PubConn, model.id);
                        if (task.taskstate == (int)Dyd.BaseService.TaskManager.Core.EnumTaskState.Running)
                        {

                            throw new Exception("当前任务在运行中,请停止后提交");
                        }
                        if (change == -1)
                        {
                            model.taskversion = dalversion.GetVersion(PubConn, model.id) + 1;
                        }
                        model.taskupdatetime = DateTime.Now;
                        dal.UpdateTask(PubConn, model);
                        if (change == -1)
                        {
                            dalversion.Add(PubConn, new tb_version_model()
                            {
                                taskid = model.id,
                                version = model.taskversion,
                                versioncreatetime = DateTime.Now,
                                zipfile = dllbyte,
                                zipfilename = System.IO.Path.GetFileName(filename)
                            });
                        }
                        tempdatadal.UpdateByTaskID(PubConn, new tb_tempdata_model()
                        {
                            taskid = model.id,
                            tempdatajson = tempdatajson,
                            tempdatalastupdatetime = DateTime.Now
                        });
                        return RedirectToAction("index");
                    }
                }
                catch (Exception exp)
                {
                    ModelState.AddModelError("", exp.Message);
                    return View();
                }
            });
        }

        public JsonResult ChangeTaskState(int id, int nodeid, int state)
        {
            return this.Visit(Core.EnumUserRole.Admin, () =>
            {
                tb_command_dal dal = new tb_command_dal();

Dyd.BaseService.TaskManager.Web/Views/Log/ErrorLog.cshtml
@using Webdiyer.WebControls.Mvc
@using Dyd.BaseService.TaskManager.Domain.Model;
@model PagedList<Dyd.BaseService.TaskManager.Domain.Model.tb_errorinfo_model>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<tb_task_model> Task = ViewBag.Task as List<tb_task_model>;
    List<tb_node_model> Node = ViewBag.Node as List<tb_node_model>;
    List<tb_user_model> User = ViewBag.User as List<tb_user_model>;
    

}
<div class="head">
    <div class="title">
        错误列表 @Html.Raw(Dyd.BaseService.TaskManager.Web.Models.Common.HelpHtml("只用于显示整个任务调度平台的所有错误，包含业务错误和平台系统级错误，这些错误在日志列表中也会有存档。错误日志可以定期在数据库中清理"))
    </div>
</div>
<div>
    @using (Html.BeginForm("Errorlog", "Log", FormMethod.Get))
    {
        <div class="item_list">
            <ul>
                <li>
                    <label>错误ID</label>
                    <input type="text" name="id" value="@(ViewBag.id>=0?ViewBag.id:"")" />
                </li>
                 <li>
                    <label>关键字</label>
                    <input type="text" name="keyword" value="@(string.IsNullOrEmpty(ViewBag.keyword)?"":ViewBag.keyword)" />
                </li>
                <li>
                    <label>任务</label>
                    <select name="taskid">
                        <option value="-1">请选择</option>
                        @foreach (var t in Task)
                        { 
                            <option value="@t.id"  @(ViewBag.taskid==t.id?"selected='selected'":"")>@t.taskname</option>
                        }
                    </select>
                </li>
                <li>
                    <label>节点</label>
                    <select name="nodeid">
                        <option value="-1">请选择</option>
                        @foreach (var n in Node)
                        { 
                            <option value="@n.id"  @(ViewBag.nodeid==n.id?"selected='selected'":"")>@n.nodename</option>
                        }
                    </select>
                </li>
                <li>
                    <label>错误类型</label>
                    <select name="errortype">
                        <option value="-1">请选择</option>
                        @foreach (var value in Enum.GetValues(typeof(XXF.BaseService.TaskManager.SystemRuntime.EnumTaskLogType)))
                        {
                            object[] objAttrs = value.GetType().GetField(value.ToString()).GetCustomAttributes(typeof(System.ComponentModel.DescriptionAttribute), true);
                            if (objAttrs != null && 
                                objAttrs.Length > 0)
                            {
                                System.ComponentModel.DescriptionAttribute descAttr = objAttrs[0] as System.ComponentModel.DescriptionAttribute;
                                <option value="@((int)value)" @(ViewBag.errortype==(int)value?"selected='selected'":"")>@descAttr.Description</option>
                            }
                        }
                    </select>
                </li>
                 <li>
                    <label>创建时间</label><input type="text" class="text" autocomplete="off"name="CStime" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss',minDate:'1900-01-01',readOnly:true})" value="@(string.IsNullOrEmpty(ViewBag.CStime)?"":ViewBag.CStime)"/>
                    至
                <input type="text" class="text" autocomplete="off" name="CEtime" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss',minDate:'1900-01-01',readOnly:true})" value="@(string.IsNullOrEmpty(ViewBag.CEtime)?"":ViewBag.CEtime)"/>
                </li>
                <li class="search">
                 <input type="submit" class="btn1" value="搜索" accesskey="S" /></li>
            </ul>
        </div>
    }
    <table>
        <tr>
            <th>id</th>
            <th>任务名</th>
            <th>节点名</th>
            <th>用户名</th>
            <th style="width:60%">错误内容</th>
            <th>错误时间</th>
            <th>错误类型</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.error_model.id</td>
                <td><a href="@Url.Action("Index", "Task", new { taskid = item.error_model.taskid })">@item.taskname [@item.error_model.taskid]</a></td>
                <td>@item.tasknodename [@item.error_model.nodeid]</td>
                <td>@item.taskcreateusername</td>
                <td title="@item.error_model.msg">@XXF.Extensions.StringMehtodHelper.SubString2(item.error_model.msg,200)</td>
                <td>@item.error_model.errorcreatetime</td>
                <td>@(Dyd.BaseService.TaskManager.Core.EnumUtils<XXF.BaseService.TaskManager.SystemRuntime.EnumTaskLogType>.GetText((XXF.BaseService.TaskManager.SystemRuntime.EnumTaskLogType)item.error_model.errortype))</td>
            </tr>
        }
    </table>
    <div class="total pt10">
    <div class="fl">共<em>@Model.TotalPageCount</em>页<em>@Model.TotalItemCount</em>条记录，当前为第<em>@Model.CurrentPageIndex</em>页</div>
        @Html.Pager(Model,new PagerOptions{PageIndexParameterName = "pageindex",ShowPageIndexBox = true,PageIndexBoxType = PageIndexBoxType.TextBox, CssClass="mvcPager"})
    </div>
</div>

Dyd.BaseService.TaskManager.Web/Views/Log/Log.cshtml
@using Webdiyer.WebControls.Mvc
@using Dyd.BaseService.TaskManager.Domain.Model;
@model PagedList<Dyd.BaseService.TaskManager.Domain.Model.tb_loginfo_model>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<tb_task_model> Task = ViewBag.Task as List<tb_task_model>;
    List<tb_node_model> Node = ViewBag.Node as List<tb_node_model>;
}
<div class="head">
    <div class="title">
        日志列表 @Html.Raw(Dyd.BaseService.TaskManager.Web.Models.Common.HelpHtml("用于显示整个任务平台的日常日志，包含错误日志和系统日志，便于排查和分析平台的问题和运行情况。日志用于存档，可定期从数据库中清理。"))
    </div>
</div>
<div>
    @using (Html.BeginForm("Log", "Log",FormMethod.Get))
    {
        <div class="item_list">
            <ul>
                <li>
                    <label>日志ID</label>
                    <input type="text" name="id" value="@(ViewBag.id>=0?ViewBag.id:"")" />
                </li>
                <li>
                    <label>关键字</label>
                    <input type="text" name="keyword" value="@(string.IsNullOrEmpty(ViewBag.keyword)?"":ViewBag.keyword)" />
                </li>
                <li>
                    <label>任务</label>
                    <select name="taskid">
                        <option value="-1">请选择</option>
                        @foreach (var t in Task)
                        { 
                            <option value="@t.id" @(ViewBag.taskid==t.id?"selected='selected'":"")>@t.taskname</option>
                        }
                    </select>
                </li>
                <li>
                    <label>节点</label>
                    <select name="nodeid">
                        <option value="-1">请选择</option>
                        @foreach (var n in Node)
                        { 
                            <option value="@n.id" @(ViewBag.nodeid==n.id?"selected='selected'":"")>@n.nodename</option>
                        }
                    </select>
                </li>
                <li>
                    <label>日志类型</label>
                    <select name="logtype">
                        <option value="-1">请选择</option>
                        @foreach (var value in Enum.GetValues(typeof(XXF.BaseService.TaskManager.SystemRuntime.EnumTaskLogType)))
                        {
                            object[] objAttrs = value.GetType().GetField(value.ToString()).GetCustomAttributes(typeof(System.ComponentModel.DescriptionAttribute), true);
                            if (objAttrs != null && 
                                objAttrs.Length > 0)
                            {
                                System.ComponentModel.DescriptionAttribute descAttr = objAttrs[0] as System.ComponentModel.DescriptionAttribute;
                                <option value="@((int)value)" @(ViewBag.logtype==(int)value?"selected='selected'":"")>@descAttr.Description</option>
                            }
                        }
                    </select>
                </li>
                 <li>
                    <label>创建时间</label><input type="text" class="text" autocomplete="off"name="CStime" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss',minDate:'1900-01-01',readOnly:true})"  value="@(string.IsNullOrEmpty(ViewBag.CStime)?"":ViewBag.CStime)"/>
                    至
                <input type="text" class="text" autocomplete="off" name="CEtime" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss',minDate:'1900-01-01',readOnly:true})"  value="@(string.IsNullOrEmpty(ViewBag.CEtime)?"":ViewBag.CEtime)"/>
                </li>
                
                <li class="search">
                 <input type="submit" class="btn1" value="搜索" accesskey="S" /></li>
            </ul>
        </div>
    }
    <table>
        <tr>
            <th>日志ID</th>
            <th>任务名</th>
            <th>节点名</th>
            <th>用户名</th>
            <th style="width:60%">内容</th>
            <th>时间</th>
            <th>类型</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.log_model.id</td>
                <td><a href="@Url.Action("Index", "Task", new { taskid = item.log_model.taskid })">@item.taskname [@item.log_model.taskid]</a></td>
                <td>@item.tasknodename [@item.log_model.nodeid]</td>
                <td>@item.taskusername</td>
                <td title="@item.log_model.msg">@Html.Raw((item.log_model.logtype == (int)XXF.BaseService.TaskManager.SystemRuntime.EnumTaskLogType.CommonError ||item.log_model.logtype==(int)XXF.BaseService.TaskManager.SystemRuntime.EnumTaskLogType.SystemError) ?
                string.Format("<b style='color:red'>{0}</b>",XXF.Extensions.StringMehtodHelper.SubString2(item.log_model.msg,300)): XXF.Extensions.StringMehtodHelper.SubString2(item.log_model.msg,300))</td>
                <td>@(item.log_model.logcreatetime)</td>
                <td>@(Dyd.BaseService.TaskManager.Core.EnumUtils<XXF.BaseService.TaskManager.SystemRuntime.EnumTaskLogType>.GetText((XXF.BaseService.TaskManager.SystemRuntime.EnumTaskLogType)item.log_model.logtype))</td>
            </tr>
        }
    </table>
    <div class="total pt10">
    <div class="fl">共<em>@Model.TotalPageCount</em>页<em>@Model.TotalItemCount</em>条记录，当前为第<em>@Model.CurrentPageIndex</em>页</div>
        @Html.Pager(Model,new PagerOptions{PageIndexParameterName = "pageindex",ShowPageIndexBox = true,PageIndexBoxType = PageIndexBoxType.TextBox, CssClass="mvcPager"})
    </div>
</div>