Dyd.BaseService.TaskManager.Web/Controllers/CommandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dyd.BaseService.TaskManager.Domain.Model;
using Dyd.BaseService.TaskManager.Domain.Dal;
using XXF.Db;
using Dyd.BaseService.TaskManager.Web.Models;
using Webdiyer.WebControls.Mvc;

namespace Dyd.BaseService.TaskManager.Web.Controllers
{
    [Authorize]
    public class CommandController : BaseWebController
    {
        //
        // GET: /Command/

        public ActionResult Index(int taskid = -1, int commandstate = -1, int nodeid = -1, int pagesize = 10, int pageindex = 1)
        {
            return this.Visit(Core.EnumUserRole.Admin, () =>
            {
                ViewBag.taskid = taskid; ViewBag.commandstate = commandstate; ViewBag.nodeid = nodeid; ViewBag.pagesize = pagesize; ViewBag.pageindex = pageindex;
                tb_command_dal dal = new tb_command_dal();
                PagedList<tb_command_model_Ex> pageList = null;
                int count = 0;
                using (DbConn PubConn = DbConfig.CreateConn(Config.TaskConnectString))
                {
                    PubConn.Open();
                    List<tb_command_model_Ex> List = dal.GetList(PubConn, commandstate, taskid, nodeid, pagesize, pageindex, out count);
                    List<tb_task_model> Task = new tb_task_dal().GetListAll(PubConn);
                    List<tb_node_model> Node = new tb_node_dal().GetListAll(PubConn);
                    ViewBag.Node = Node;
                    ViewBag.Task = Task;
                    pageList = new PagedList<tb_command_model_Ex>(List, pageindex, pagesize, count);
                }
                return View(pageList);
            });
        }

        public ActionResult Add()
        {
            return this.Visit(Core.EnumUserRole.Admin, () =>
            {
                using (DbConn PubConn = DbConfig.CreateConn(Config.TaskConnectString))
                {
                    PubConn.Open();
                    List<tb_task_model> Task = new tb_task_dal().GetListAll(PubConn);
                    List<tb_node_model> Node = new tb_node_dal().GetListAll(PubConn);
                    ViewBag.Node = Node;
                    ViewBag.Task = Task;
                    return View();
                }
            });
        }

        [HttpPost]
        public ActionResult Add(tb_command_model model)
        {
            return this.Visit(Core.EnumUserRole.Admin, () =>
            {
                tb_command_dal dal = new tb_command_dal();
                using (DbConn PubConn = DbConfig.CreateConn(Config.TaskConnectString))
                {
                    PubConn.Open();
                    model.commandcreatetime = DateTime.Now;
                    dal.Add(PubConn, model);
                }
                return RedirectToAction("index");
            });
        }

        public ActionResult Update(int id)
        {
            return this.Visit(Core.EnumUserRole.Admin, () =>
            {
                using (DbConn PubConn = DbConfig.CreateConn(Config.TaskConnectString))
                {
                    PubConn.Open();
                    tb_command_dal dal = new tb_command_dal();
                    tb_command_model_Ex model = dal.GetOneCommand(PubConn, id);
                    List<tb_node_model> Node = new tb_node_dal().GetListAll(PubConn);
                    ViewBag.Node = Node;
                    return View(model);
                }
            });
        }

        [HttpPost]
        public ActionResult Update(tb_command_model model)
        {
            return this.Visit(Core.EnumUserRole.Admin, () =>
            {
                tb_command_dal dal = new tb_command_dal();
                using (DbConn PubConn = DbConfig.CreateConn(Config.TaskConnectString))
                {
                    PubConn.Open();
                    model.commandcreatetime = DateTime.Now;
                    dal.UpdateCommand(PubConn, model);
                }
                return RedirectToAction("index");
            });
        }

        public JsonResult Delete(int id)
        {
            return this.Visit(Core.EnumUserRole.Admin, () =>
            {
                using (DbConn PubConn = DbConfig.CreateConn(Config.TaskConnectString))
                {
                    PubConn.Open();
                    tb_command_dal dal = new tb_command_dal();
                    dal.Delete(PubConn, id);
                    return Json(new { code = 1, msg = "Success" });
                }
            });
        }
    }
}

Dyd.BaseService.TaskManager.Web/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dyd.BaseService.TaskManager.Domain.Model;
using Dyd.BaseService.TaskManager.Domain.Dal;
using XXF.Db;
using Dyd.BaseService.TaskManager.Web.Models;
using Webdiyer.WebControls.Mvc;
using System.Drawing;
using System.IO;
using Dyd.BaseService.TaskManager.Core;
using XXF.Extensions;

namespace Dyd.BaseService.TaskManager.Web.Controllers
{
    [Authorize]
    public class TaskController : BaseWebController
    {
        //
        // GET: /Task/

        public ActionResult Index(string taskid, string keyword, string CStime,string CEtime, int categoryid = -1, int nodeid = -1, int userid = -1, int state = -999, int pagesize = 10, int pageindex = 1)
        {
            return this.Visit(Core.EnumUserRole.None, () =>
            {
                ViewBag.taskid = taskid;
                ViewBag.keyword = keyword;
                ViewBag.CStime = CStime;
                ViewBag.CEtime = CEtime;
                ViewBag.categoryid = categoryid;
                ViewBag.nodeid = nodeid;
                ViewBag.userid = userid;
                ViewBag.state = state;
                ViewBag.pagesize = pagesize;
                ViewBag.pageindex = pageindex;

                tb_task_dal dal = new tb_task_dal();
                PagedList<tb_tasklist_model> pageList = null;
                int count = 0;
                using (DbConn PubConn = DbConfig.CreateConn(Config.TaskConnectString))
                {
                    PubConn.Open();
                    List<tb_tasklist_model> List = dal.GetList(PubConn,taskid, keyword, CStime,CEtime, categoryid, nodeid, userid, state, pagesize, pageindex, out count);
                    pageList = new PagedList<tb_tasklist_model>(List, pageindex, pagesize, count);
                    List<tb_node_model> Node = new tb_node_dal().GetListAll(PubConn);
                    List<tb_category_model> Category = new tb_category_dal().GetList(PubConn, "");
                    List<tb_user_model> User = new tb_user_dal().GetAllUsers(PubConn);
                    ViewBag.Node = Node;
                    ViewBag.Category = Category;
                    ViewBag.User = User;
                }
                return View(pageList);
            });
        }

        public ActionResult Add()
        {
            return this.Visit(Core.EnumUserRole.Admin, () =>
            {
                using (DbConn PubConn = DbConfig.CreateConn(Config.TaskConnectString))
                {
                    PubConn.Open();
                    List<tb_category_model> Category = new tb_category_dal().GetList(PubConn, "");
                    List<tb_node_model> Node = new tb_node_dal().GetListAll(PubConn);
                    List<tb_user_model> User = new tb_user_dal().GetAllUsers(PubConn);
                    ViewBag.Node = Node;
                    ViewBag.Category = Category;
                    ViewBag.User = User;
                    return View();
                }
            });
        }

        
        public JsonResult CalcRunTime(string CronExpression,int count=5)
        {
            Quartz.CronTrigger trigger = new Quartz.CronTrigger();
            trigger.CronExpressionString = CronExpression;
            List<string> list = new List<string>();
            //注意：这里是utc时间
            trigger.StartTimeUtc = DateTime.UtcNow;
            DateTime? now = trigger.StartTimeUtc;
            for (int i = 0; i < count; i++)
            {
                now = trigger.GetFireTimeAfter(now);
                //要转回本地时间
                list.Add(TimeZone.CurrentTimeZone.ToLocalTime(now.Value).ToString("yyyy/M/d HH:mm:ss"));

            }
            return Json(list,JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Add(HttpPostedFileBase TaskDll, tb_task_model model, string tempdatajson)
        {
            return this.Visit(Core.EnumUserRole.Admin, () =>
            {
                string filename = TaskDll.FileName;
                Stream dll = TaskDll.InputStream;
                byte[] dllbyte = new byte[dll.Length];
                dll.Read(dllbyte, 0, Convert.ToInt32(dll.Length));
                tb_task_dal dal = new tb_task_dal();
                tb_version_dal dalversion = new tb_version_dal();
                tb_tempdata_dal tempdatadal = new tb_tempdata_dal();
                //model.taskcreateuserid = Common.GetUserId(this);
                using (DbConn PubConn = DbConfig.CreateConn(Config.TaskConnectString))
                {
                    PubConn.Open();
                    model.taskcreatetime = DateTime.Now;
                    model.taskversion = 1;
                    int taskid = dal.AddTask(PubConn, model);
                    dalversion.Add(PubConn, new tb_version_model()
                    {
                        taskid = taskid,
                        version = 1,
                        versioncreatetime = DateTime.Now,
                        zipfile = dllbyte,
                        zipfilename = System.IO.Path.GetFileName(filename)
                    });
                    tempdatadal.Add(PubConn, new tb_tempdata_model()
                    {
                        taskid = taskid,
                        tempdatajson = tempdatajson,
                        tempdatalastupdatetime = DateTime.Now
                    });
                }
                return RedirectToAction("index");
            });
        }

        public ActionResult Update(int taskid)
        {
            return this.Visit(Core.EnumUserRole.None, () =>
            {
                using (DbConn PubConn = DbConfig.CreateConn(Config.TaskConnectString))
                {
                    PubConn.Open();
                    tb_task_dal dal = new tb_task_dal();
                    tb_task_model model = dal.GetOneTask(PubConn, taskid);
                    tb_tempdata_model tempdatamodel = new tb_tempdata_dal().GetByTaskID(PubConn, taskid);
                    List<tb_version_model> Version = new tb_version_dal().GetTaskVersion(PubConn, taskid);
                    List<tb_category_model> Category = new tb_category_dal().GetList(PubConn, "");
                    List<tb_node_model> Node = new tb_node_dal().GetListAll(PubConn);
                    List<tb_user_model> User = new tb_user_dal().GetAllUsers(PubConn);
                    ViewBag.Node = Node;
                    ViewBag.Category = Category;
                    ViewBag.Version = Version;
                    ViewBag.User = User;
                    ViewBag.TempData = tempdatamodel;
                    return View(model);
                }
            });
        }

        [HttpPost]
        public ActionResult Update(HttpPostedFileBase TaskDll, tb_task_model model, string tempdatajson)
        {
            return this.Visit(Core.EnumUserRole.Admin, () =>
            {
                try
                {
                    tb_task_dal dal = new tb_task_dal();
                    tb_version_dal dalversion = new tb_version_dal();
                    tb_tempdata_dal tempdatadal = new tb_tempdata_dal();
                    byte[] dllbyte = null;
                    string filename = "";
                    int change = model.taskversion;
                    if (change == -1)
                    {
                        if (TaskDll == null)
                        {
                            throw new Exception("没有文件！");
                        }
                        filename = TaskDll.FileName;
                        Stream dll = TaskDll.InputStream;
                        dllbyte = new byte[dll.Length];
                        dll.Read(dllbyte, 0, Convert.ToInt32(dll.Length));
                        //model.taskcreateuserid = Common.GetUserId(this);
                    }
                    using (DbConn PubConn = DbConfig.CreateConn(Config.TaskConnectString))
                    {
                        PubConn.Open();
                        var task = dal.GetOneTask(PubConn, model.id);
                        if (task.taskstate == (int)Dyd.BaseService.TaskManager.Core.EnumTaskState.Running)
                        {

                            throw new Exception("当前任务在运行中,请停止后提交");
                        }
                        if (change == -1)
                        {
                            model.taskversion = dalversion.GetVersion(PubConn, model.id) + 1;
                        }
                        model.taskupdatetime = DateTime.Now;
                        dal.UpdateTask(PubConn, model);
                        if (change == -1)
                        {
                            dalversion.Add(PubConn, new tb_version_model()
                            {
                                taskid = model.id,
                                version = model.taskversion,
                                versioncreatetime = DateTime.Now,
                                zipfile = dllbyte,
                                zipfilename = System.IO.Path.GetFileName(filename)
                            });
                        }
                        tempdatadal.UpdateByTaskID(PubConn, new tb_tempdata_model()
                        {
                            taskid = model.id,
                            tempdatajson = tempdatajson,
                            tempdatalastupdatetime = DateTime.Now
                        });
                        return RedirectToAction("index");
                    }
                }
                catch (Exception exp)
                {
                    ModelState.AddModelError("", exp.Message);
                    return View();
                }
            });
        }

        public JsonResult ChangeTaskState(int id, int nodeid, int state)
        {
            return this.Visit(Core.EnumUserRole.Admin, () =>
            {
                tb_command_dal dal = new tb_command_dal();

Dyd.BaseService.TaskManager.Web/Views/Command/Add.cshtml
@using Dyd.BaseService.TaskManager.Domain.Model;
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<tb_task_model> Task = ViewBag.Task as List<tb_task_model>;
    List<tb_node_model> Node = ViewBag.Node as List<tb_node_model>;
}

<script>
    function sub() {
        if ($("#nodename").val() == "") {
            alert("请填写节点名称！");
            return false;
        }
        var nodeip = $("#nodeip").val();
        if (nodeip == "") {
            alert("请填写节点IP！");
            return false;
        }
        else {
            //ip地址
            var exp = /^(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])\.(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])\.(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])\.(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])$/;
            var reg = nodeip.match(exp);
            if (reg == null) {
                alert("IP地址不合法！");
                return false;
            }
        }
    }
</script>
<div class="head">
    <div class="title">
        新增命令 @Html.Raw(Dyd.BaseService.TaskManager.Web.Models.Common.HelpHtml(""))
    </div>
</div>
<div>
    @using (Html.BeginForm("Add", "Command", FormMethod.Post))
    {
    <ul class="mydetail">
        <li>
            <label>命令名称</label>
            <select name="commandname">
                <option value="ReStartTask">ReStartTask</option>
                <option value="StopTask">StopTask</option>
                <option value="StartTask">StartTask</option>
                <option value="UninstallTask">UninstallTask</option>
            </select>
        </li>
        <li>
            <label>任务</label>
            <select name="taskid">
                @foreach (var t in Task)
                { 
                    <option value="@t.id">@t.taskname</option>
                }
            </select>
        </li>
        <li>
            <label>节点</label>
            <select name="nodeid">
                @foreach (var n in Node)
                { 
                    <option value="@n.id">@n.nodename</option>
                }
            </select>
        </li>
        <li>
            <label>命令JSON</label><textarea id="command" name="command" ></textarea>
        </li>
        <li>
            <label>表达式</label>
            <select name="commandstate">
                <option value="0">None</option>
                <option value="1">Error</option>
                <option value="2">Success</option>
            </select>
        </li>
        <li>
            <input type="submit" class="btn1" value="提交" />
        </li>
    </ul>
    }
</div>

Dyd.BaseService.TaskManager.Web/Views/Command/Index.cshtml
@using Webdiyer.WebControls.Mvc
@using Dyd.BaseService.TaskManager.Domain.Model;
@model PagedList<Dyd.BaseService.TaskManager.Domain.Model.tb_command_model_Ex>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<tb_task_model> Task = ViewBag.Task as List<tb_task_model>;
    List<tb_node_model> Node = ViewBag.Node as List<tb_node_model>;
}
<script>
    function Delete(id)
    {
        if (confirm("确定删除吗？") == true)
        {
            $.ajax({
                url: "@Url.Action("delete", "command")",
                type: "post",
                data: {
                    id:id
                },
                success: function (data) {
                    if (data.code == 1) {
                        alert("成功！");
                        window.location.reload();
                    }
                    else {
                        alert(data.msg);
                    }
                }
            })
        }
    }
</script>

<div class="head">
    <div class="title">
        命令列表 @Html.Raw(Dyd.BaseService.TaskManager.Web.Models.Common.HelpHtml("用于显示任务管理站点和任务节点之间的命令列表，及命令执行情况。这些命令只用于存档，可以定期从数据库中清理。【注：节点不会执行已经过期的命令。】"))
    </div>
</div>
<div class="orderlist m10 myorder">
    @using (Html.BeginForm("Index", "command",FormMethod.Get ))
    {
        <div class="item_list">
            <ul>
                <li>
                    <label>任务</label>
                    <select name="taskid">
                        <option value="-1">请选择</option>
                        @foreach (var t in Task)
                        { 
                            <option value="@t.id"  @(ViewBag.taskid==t.id?"selected='selected'":"")>@t.taskname</option>
                        }
                    </select>
                </li>
                <li>
                    <label>节点</label>
                    <select name="nodeid">
                        <option value="-1">请选择</option>
                        @foreach (var n in Node)
                        { 
                            <option value="@n.id" @(ViewBag.nodeid==n.id?"selected='selected'":"")>@n.nodename</option>
                        }
                    </select>
                </li>
                <li>
                    <label>执行状态</label>
                    <select name="commandstate">
                        <option value="-1">请选择</option>
                        @foreach (var value in Enum.GetValues(typeof(Dyd.BaseService.TaskManager.Core.EnumTaskCommandState)))
                        {
                            object[] objAttrs = value.GetType().GetField(value.ToString()).GetCustomAttributes(typeof(System.ComponentModel.DescriptionAttribute), true);
                            if (objAttrs != null && 
                                objAttrs.Length > 0)
                            {
                                System.ComponentModel.DescriptionAttribute descAttr = objAttrs[0] as System.ComponentModel.DescriptionAttribute;
                                <option value="@((int)value)" @(ViewBag.commandstate==(int)value?"selected='selected'":"")>@descAttr.Description</option>
                            }
                        }
                    </select>
                </li>
                <li class="search">
                    <input type="submit" class="btn1" value="搜索" accesskey="S" />
                </li>
            </ul>
        </div>
    }
    <div class="tab_cont">
        <a href="@Url.Action("add", "command")" class="btn1" >新增</a>
        <div class="list">
            <table>
                <tr>
                    <th>id</th>
                    <th>任务名</th>
                    <th>命令json</th>
                    <th>命令名称</th>
                    <th>状态</th>
                    <th>节点ID</th>
                    <th>操作</th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.id</td>
                        <td><a href="@Url.Action("Index", "Task", new { taskid = item.taskid })">@item.taskname [@item.taskid]</a></td>
                        <td>@item.command</td>
                        <td>@item.commandname</td>
                        <td>@(Dyd.BaseService.TaskManager.Core.EnumUtils<Dyd.BaseService.TaskManager.Core.EnumTaskCommandState>.GetText((Dyd.BaseService.TaskManager.Core.EnumTaskCommandState)item.commandstate))</td>
                        <td>@item.nodename [@item.nodeid]</td>
                        <td>
                            <a href="@Url.Action("Update", "Command", new { id = item.id })">修改</a>
                            <input type="button" onclick="Delete('@item.id    ')" value="删除" />
                        </td>
                    </tr>
                }
            </table>
            <div class="total pt10">
                <div class="fl">共<em>@Model.TotalPageCount</em>页<em>@Model.TotalItemCount</em>条记录，当前为第<em>@Model.CurrentPageIndex</em>页</div>
                @Html.Pager(Model, new PagerOptions { PageIndexParameterName = "pageindex", ShowPageIndexBox = true, PageIndexBoxType = PageIndexBoxType.TextBox, CssClass = "mvcPager" })
            </div>
        </div>
    </div>
</div>

Dyd.BaseService.TaskManager.Web/Views/Command/Update.cshtml
@using Dyd.BaseService.TaskManager.Domain.Model;
@model Dyd.BaseService.TaskManager.Domain.Model.tb_command_model_Ex
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<tb_node_model> Node = ViewBag.Node as List<tb_node_model>;
    
}
<div class="head">
    <div class="title">
        修改 @Html.Raw(Dyd.BaseService.TaskManager.Web.Models.Common.HelpHtml(""))
    </div>
</div>
<div>
    @using (Html.BeginForm("Update", "Command", FormMethod.Post))
    {
    <ul  class="mydetail">
        <li>
            <label>命令名称</label>
            <select name="commandname">
                <option value="ReStartTask" @Html.Raw(@Model.commandname=="ReStartTask"?"selected=selected":"")>ReStartTask</option>
                <option value="StopTask" @Html.Raw(@Model.commandname=="StopTask"?"selected=selected":"")>StopTask</option>
                <option value="StartTask" @Html.Raw(@Model.commandname=="StartTask"?"selected=selected":"")>StartTask</option>
                <option value="UninstallTask" @Html.Raw(@Model.commandname=="UninstallTask"?"selected=selected":"")>UninstallTask</option>
            </select>
        </li>
        <li>
            <label>任务</label><span>@Model.taskname</span>
        </li>
        <li>
            <label>节点</label>
            <select name="nodeid">
                @foreach (var n in Node)
                { 
                    <option value="@n.id" @Html.Raw(@Model.nodeid==n.id?"selected=selected":"")>@n.nodename</option>
                }
            </select>
        </li>
        <li>
            <label>命令JSON</label><textarea id="command" name="command">@Model.command</textarea>
        </li>
        <li>
            <label>表达式</label>
            <select name="commandstate">
                <option value="0" @Html.Raw(@Model.commandstate==0?"selected=selected":"")>None</option>
                <option value="1" @Html.Raw(@Model.commandstate==1?"selected=selected":"")>Error</option>
                <option value="2" @Html.Raw(@Model.commandstate==2?"selected=selected":"")>Success</option>
            </select>
        </li>
        <li>
            <input type="submit" class="btn1" value="提交" />
        </li>
    </ul>
    }
</div>